stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - fake.csv
    - true.csv
  process_data:
    cmd: python process_data.py
    deps:
    - fake.csv
    - true.csv
    - process_data.py
    outs:
    - data_processed.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data_processed.csv
    metrics:
    - metrics.json:
        cache: false
